base.url=http://localhost:${quarkus.wiremock.devservices.port}

image.service.url=http://localhost:${quarkus.wiremock.devservices.port}/image-service/images
repos.service.url=http://localhost:${quarkus.wiremock.devservices.port}/repos-service/repos

# joogle and jahoo authorization servers
joogle.service.url=${base.url}/joogle
jahoo.service.url=${base.url}/jahooo

auth-server.keycloakMock.client-id=quarkus-flow
auth-server.keycloakMock.client-secret=dummy-client-secret
auth-server.keycloakMock.base-url=http://localhost:${quarkus.wiremock.devservices.port}/auth/realms/test-realm/protocol/openid-connect/token

auth-server.joogle.client-id=quarkus-flow
auth-server.joogle.client-secret=joogle-client-secret
auth-server.joogle.base-url=${base.url}

auth-server.jahoo.client-id=quarkus-flow
auth-server.jahoo.client-secret=jahoo-client-secret
auth-server.jahoo.base-url=${base.url}

quarkus.wiremock.devservices.files-mapping=src/main/resources


quarkus.native.resources.includes=openapi-oauth2.json
